[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable build cache
[build.processing]
  skip_processing = false

[[build.processing.cache]]
  paths = [".next/cache"]